# Generated by Django 4.2.13 on 2024-06-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=5),
        ),
    ]
